---
- name: "Download Kibana's rpm"
  when: ansible_facts.virtualization_type != "docker"
  include: rpm.yml

- name: Install Kibana tar.gz (on Docker)
  when: ( ansible_facts.virtualization_type == "docker" )
        # or ( ansible_facts.env.container == "podman" )
        # or ( ansible_connection == "community.docker.docker" )
  include: targz.yml
