---
- name: "Download Kibana's rpm"
  get_url:
    # url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-x86_64.rpm"
    url: "https://ntl.run0ut.ru/cicd/kibana-{{ kibana_version }}-x86_64.rpm"
    dest: "/tmp/kibana-{{ kibana_version }}-x86_64.rpm"
  register: download_kibana
  until: download_kibana is succeeded

- name: Install Kibana RPM
  block:
    - name: Install latest Kibana
      become: true
      yum:
        name: "/tmp/kibana-{{ kibana_version }}-x86_64.rpm"
        state: latest
  rescue:
    - name: Uninstall Kibana
      become: true
      yum:
        name: "kibana"
        state: removed
    - name: Reinstall Kibana
      become: true
      yum:
        name: "/tmp/kibana-{{ kibana_version }}-x86_64.rpm"
        state: present

- name: Configure Kibana
  become: true
  vars:
    - kibana_home: "/usr/share/kibana"
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    mode: 0644
  notify: restart Kibana systemd

- name: Flush handlers
  meta: flush_handlers
