namespace: netology
name: study_collection
version: 3.0.0
readme: README.md
authors:
- Sergey shadurskiy <s.shadurskiy@gmail.com>
description: Simple collection made as a home assignment
license:
- MIT
license_file: ''
tags: []
dependencies: {}
repository: https://github.com/run0ut/netology_study_collection
documentation: None
homepage: None
issues: None
build_ignore: []

