- name: "Create {{ homework }}-vm1"
  yc_create_instance:
    network_interface: "net-ru-central1-a"
    name: "{{ homework }}-vm1"
    image_family: "ubuntu-2004-lts"
    cores: 2
    memory: 4
    status: "running"

- name: Refresh Inventory
  meta: refresh_inventory