- name: "Create {{ vm_name }}"
  yc_create_instance:
    network_interface: "{{ network_interface }}"
    name: "{{ vm_name }}"
    image_family: "{{ image_family }}"
    cores: "{{ cores }}"
    memory: "{{ memory }}"
    status: "running"

- name: Refresh Inventory
  meta: refresh_inventory