- name: Installing necessary packages
  apt: >
      name={{ item }}
      state=present
      update_cache=yes
  with_items:
      - conntrack
      - docker.io
      - iproute2
      - socat

- name: Get kube version
  uri:
    url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
    return_content: yes
  register: kube_version
- name: Download kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kube_version.content }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
- name: Download minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'

- name: Check Kuber version
  command: minikube version
  register: check_minikube_version
  changed_when: False
- name: Print minikube version
  debug: 
    var: check_minikube_version.stdout_lines

- name: Check if kubectl bash completion is present
  stat:
    path: "/etc/bash_completion.d/kubectl"
  register: kubectl_bash_completion_present
- name: Print last
  debug:
    var: kubectl_bash_completion_present.stat.exists
- name: Configure bash completion
  shell: kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null
  when: kubectl_bash_completion_present.stat.exists == false

- name: Check if minikube is running
  shell: minikube status | grep host.*Running
  register: check_minikube_server
  changed_when: False
  failed_when: False
- name: Run minikube
  block:
  - name: Run minikube
    command: 
      cmd: minikube start --vm-driver=none --apiserver-ips {{ ansible_host }} {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} 127.0.0.1
    when: check_minikube_server.rc != 0
  rescue:
  - name: Fix sysctl fs.protected_regular
    sysctl:
      name: fs.protected_regular
      value: '0'
      state: present
  - name: Rerun minikube
    command: 
      cmd: minikube start --vm-driver=none --apiserver-ips {{ ansible_host }} {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} 127.0.0.1
    when: check_minikube_server.rc != 0

- name: Get minikube status
  command: 
    cmd: minikube status
  register: get_minikube_status
  changed_when: False
  failed_when: False
- name: Print minikube status
  debug:
    var: get_minikube_status.stdout_lines

- name: Get kubectl pods
  command: 
    cmd: kubectl get pods --namespace=kube-system
  register: get_pods
  changed_when: False
  failed_when: False
- name: Print kubectl pods
  debug:
    var: get_pods.stdout_lines